title: software.nandang.sopyan.id
description: > # this means to ignore newlines until "baseurl:"
  Menulis untuk mengingat dan belajar.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Nandang Sopyan # add your name
author-img: prof.jpeg # add your photo
about-author: Penyuka Teknologi Informasi khususnya dibidang pengembangan web dan linux sistem. # add description
# social-twitter: # add your Twitter handle
# social-facebook: # add your Facebook handle
social-github: ndgspn # add your Github handle
social-linkedin: nsopyan# add your Linkedin handle
# social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
